Revert "Avoid a deadlock when deleting a server (bsc#969790)"
This reverts commit e69bab06d22148f3c6c3ecf15e3baf5a68220cdb.

Fix of bsc#969790 was a consequence of the earlier bsc#918549 - the
latter changed the order tables were locked in
rhn_server.update_needed_cache, specifically locking rhnServer first.
The change of odering opened up the chance of another deadlock when
Taskomatic's errata-cache-bunch happened concurrently to client
re-registrations. As explained in
https://github.com/SUSE/spacewalk/wiki/Bug-969790:

"There is a deadlock condition between the update_needed_cache and
delete_server stored procedures.
rhn_server.update_needed_cache() explicitly locks rhnServer table, then
DELETEs from rhnServerNeededCache (implicitly locking it).
delete_server() DELETEs from rhnServerNeededCache first and then DELETEs
from rhnServer (implicitly locking it).

The difference in locking order gives rise to the deadlock."

With the fix for bsc#918549 now reverted, the fix for bsc#969790 is also
not useful anymore (and actually dangerous). Indeed it was found to
cause a different deadlock conditon as per the log below:

ERROR:  deadlock detected
DETAIL:  Process 8479 waits for ShareLock on transaction 399669498;
blocked by process 14346.
	Process 14346 waits for AccessShareLock on tuple (60052,11) of
relation 17045 of database 16384; blocked by process 14592.
	Process 14592 waits for ShareLock on transaction 399669163;
blocked by process 8479.
	Process 8479: select * from delete_server($1)  as result
	Process 14346:
	            insert into rhnServerPackage
	            (server_id, name_id, evr_id, package_arch_id,
installtime)
	            values (1000102753,
LOOKUP_PACKAGE_NAME('rhn-org-trusted-ssl-cert'), LOOKUP_EVR(NULL, '1.0',
'10'),
	                LOOKUP_PACKAGE_ARCH('noarch'),
TO_TIMESTAMP('2020-06-07 15:45:10', 'YYYY-MM-DD HH24:MI:SS')
	            )
	Process 14592: select * from rhn_server.update_needed_cache($1)
as result

Note that delete_server blocks update_needed_cache as they both attempt
to get a lock on rhnServer.