Forward the page url to the list
It enables browsing through multiple pages.

Addressing:
ERROR com.redhat.rhn.common.errors.BadParameterExceptionHandler - Missing Parameter Error
com.redhat.rhn.frontend.action.common.BadParameterException: The parameter sid is required.