Truncate data which are longer than db allows
While this kind of problems should be rare enough
given the limits, it should definitelly not end up
as ISE.

Addressing:
SQLError: (12899, 'ORA-12899: value too large for column "SPACEWALK"."RHNXCCDFIDENT"."IDENTIFIER" (actual: 83, maximum: 80)\n
ORA-06512: at "SPACEWALK.INSERT_XCCDF_IDENT", line 7\nORA-06512: at "SPACEWALK.LOOKUP_XCCDF_IDENT", line 32\n
ORA-01403: no data found\n', 'insert into rhnXccdfRuleIdentMap (rresult_id, ident_id) values ( :rr_id, lookup_xccdf_ident(:system, :ident) )')