We need to specifically check for None when calling decode.
Addressing
  File "/usr/lib/python2.6/site-packages/spacewalk/server/importlib/importLib.py", line 623, in run
    self.preprocess()
  File "/usr/lib/python2.6/site-packages/spacewalk/server/importlib/packageImport.py", line 58, in preprocess
    self._processPackage(package)
  File "/usr/lib/python2.6/site-packages/spacewalk/server/importlib/packageImport.py", line 275, in _processPackage
    package['description'] = self._fix_encoding(package['description'])
  File "/usr/lib/python2.6/site-packages/spacewalk/server/importlib/packageImport.py", line 506, in _fix_encoding
    return text.decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'