656895 - Need to call startswith on string.
Addressing
Traceback (most recent call last):
  File "/usr/bin/rhncfg-client", line 34, in ?
    sys.exit(Main().main() or 0)
  File "/usr/share/rhn/config_common/rhn_main.py", line 67, in main
    if utils.startswith(arg, server_name_opt):
AttributeError: 'module' object has no attribute 'startswith'