fix invalid SQL statement for finding ssh-push candidates (bnc#821868)
Oracle requires all not grouped parts in the group by clause.
Fixes:
com.redhat.rhn.common.db.WrappedSQLException: ORA-00979: not a GROUP BY expression