915287 - python 2.4 does not know 'exit'
sys.exit works in python 2.6 as well

addressing:
Traceback (most recent call last):
  File /usr/sbin/rhn-profile-sync, line 54, in ?
    cli.run()
  File /usr/share/rhn/up2date_client/rhncli.py, line 66, in run
    sys.exit(self.main() or 0)
  File /usr/sbin/rhn-profile-sync, line 49, in main
    support.refresh(True)
  File /usr/share/rhn/virtualization/support.py, line 62, in refresh
    if _is_host_domain(fail_on_error):
  File /usr/share/rhn/virtualization/support.py, line 192, in _is_host_domain
    exit(1)
exceptions.TypeError: 'str' object is not callable