Preventing whole SQL string from being NULL
which caused:
ERROR:  insert or update on table "rhnpackagedeltaelement" violates foreign key constraint "rhn_pdelement_tpid_fk"
DETAIL:  Key (transaction_package_id)=(84) is not present in table "rhntransactionpackage".
STATEMENT:
            insert into rhnPackageDeltaElement
                   (package_delta_id, transaction_package_id)
            values
                   (26,
                    lookup_transaction_package(E'insert', E'apr', NULL, E'1.3.9', E'3.el6_1.2', NULL))