1148163 - fixed variable name
it masked imported module
Traceback (most recent call last):
  File "/usr/bin/spacewalk-data-fsck", line 312, in <module>
    exit_value += check_db_vs_disk(options)
  File "/usr/bin/spacewalk-data-fsck", line 109, in check_db_vs_disk
    row['checksum_type'], row['checksum'])
  File "/usr/bin/spacewalk-data-fsck", line 217, in check_disk_checksum
    h = checksum.getHashlibInstance(checksum_type, False)
AttributeError: 'str' object has no attribute 'getHashlibInstance'
bug introduced in 5dabeddf4306f61f555b6a329324dbc3b0afc8cc