Revert "ClientCertificate - make not publically used methods/attributes private"
This reverts commit 3a63347e646e057ac35b55b614155cc4cee8f8d8.

This fixes the xmlrpc error you get when you try to connect a spacewalk proxy
to the spacewalk server in version 2.8. This error is thrown because of

[TP-Processor2] ERROR org.apache.commons.digester.Digester - End event threw exception
java.lang.NoSuchMethodException: No such accessible method: addMember() on object:
  com.redhat.rhn.common.client.ClientCertificate

See also https://www.redhat.com/archives/spacewalk-list/2018-May/msg00123.html
for further information.