Revert "Avoid a deadlock when changing channel assignments (bsc#918549)"
This reverts commit b0a27c0f22c2da5054a6543563e97790691c6711.

As explained in https://github.com/spacewalkproject/spacewalk/pull/233,
the deadlock fixed by the original commit depended on a Postgres <9.5
implementation detail, namely the locking of an entire row in a parent
table on INSERT INTO a child table.

That mechanism got improved in Postgres 9.5 and the deadlock is not
reproducible any longer, rendering the solution obsolete.

It is advisable to remove the fix introduced back then because it
comes with a higher risk of causing more unrelated deadlocks:

https://www.postgresql.org/docs/12/explicit-locking.html#LOCKING-DEADLOCKS
https://github.com/spacewalkproject/spacewalk/pull/233#issuecomment-77198323

That was actually verified from a user Postgres log file, which reported
the following stack trace:

ERROR:  deadlock detected
DETAIL:  Process 8479 waits for ShareLock on transaction 399669498;
blocked by process 14346.
	Process 14346 waits for AccessShareLock on tuple (60052,11) of
relation 17045 of database 16384; blocked by process 14592.
	Process 14592 waits for ShareLock on transaction 399669163;
blocked by process 8479.
	Process 8479: select * from delete_server($1)  as result
	Process 14346:
	            insert into rhnServerPackage
	            (server_id, name_id, evr_id, package_arch_id,
installtime)
	            values (1000102753,
LOOKUP_PACKAGE_NAME('rhn-org-trusted-ssl-cert'), LOOKUP_EVR(NULL, '1.0',
'10'),
	                LOOKUP_PACKAGE_ARCH('noarch'),
TO_TIMESTAMP('2020-06-07 15:45:10', 'YYYY-MM-DD HH24:MI:SS')
	            )
	Process 14592: select * from rhn_server.update_needed_cache($1)
as result

...

LOG:  process 14592 acquired ShareLock on transaction 399669163 after
16173.154 ms
CONTEXT:  while locking tuple (60052,11) in relation "rhnserver"
	SQL statement "select id                  from rhnServer where
id = server_id_in for update"
	PL/pgSQL function rhn_server.update_needed_cache(numeric) line 5
at SQL statement

Note the last lines: the deadlock involved update_needed_cache exactly
on the extra locking line added by the patch being reverted here.