Introducing an interface common for rpm, deb and mpm packages
Addressing:
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/spacewalk/server/apacheUploadServer.py", line 97, in _wrapper
    ret = function(req)
  File "/usr/share/rhn/upload_server/handlers/package_push/package_push.py", line 134, in handler
    relative_path=self.rel_package_path, org_id=self.org_id)
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnPackageUpload.py", line 164, in push_package
    importer.run()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/importlib/importLib.py", line 630, in run
    self.submit()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/importlib/packageImport.py", line 297, in submit
    self._import_signatures()
  File "/usr/lib/python2.4/site-packages/spacewalk/server/importlib/packageImport.py", line 485, in _import_signatures
    header = rhn_rpm.get_package_header(filename=full_path)
  File "/usr/lib/python2.4/site-packages/spacewalk/common/rhn_rpm.py", line 282, in get_package_header
    hdr = ts.hdrFromFdno(file_desc)
  File "/usr/lib/python2.4/site-packages/spacewalk/common/rhn_rpm.py", line 106, in hdrFromFdno
    return self.ts.hdrFromFdno(fd)
error: error reading package header