added missing import
fixing
[javac] KickstartIpRangeAction.java:93: cannot find symbol
[javac] symbol  : class KickstartData
[javac] location: class com.redhat.rhn.frontend.action.kickstart.KickstartIpRangeAction
[javac]         KickstartData ksData = cmd.getKickstartData();