1735715 - read LOBs explicitly
fixes
Traceback (most recent call last):
  File "/usr/bin/cdn-sync", line 230, in <module>
    sys.exc_info()[2])
  File "/usr/bin/cdn-sync", line 162, in <module>
    cdnsync.print_cdn_certificates_info(repos=args.show_repos)
  File "/usr/lib/python2.6/site-packages/spacewalk/cdn_tools/cdnsync.py", line 829, in print_cdn_certificates_info
    print('to str:', str(key['key']))
Exception: SYNC ERROR: attempting to display as much information as possible
 LOB variable no longer valid after subsequent fetch