Each dataset must have a different name.
Otherwise the elaborator (once bind to that name) remains
in the session. Even after another dataset has been assigned to.
Causing the consequent CSV export to fail.

Addressing:
com.redhat.rhn.common.db.datasource.MapColumnNotFoundException: Column, xid, not found in driving query results
	at com.redhat.rhn.common.db.datasource.CachedStatement.executeElaboratorBatch(CachedStatement.java:378)
	at com.redhat.rhn.common.db.datasource.CachedStatement.executeElaborator(CachedStatement.java:352)
	at com.redhat.rhn.common.db.datasource.SelectMode.elaborate(SelectMode.java:169)
	at com.redhat.rhn.common.db.datasource.ModeElaborator.elaborate(ModeElaborator.java:48)
	at com.redhat.rhn.frontend.action.CSVDownloadAction.getStreamInfo(CSVDownloadAction.java:188)
	at org.apache.struts.actions.DownloadAction.execute(DownloadAction.java:104)
	at com.redhat.rhn.frontend.action.CSVDownloadAction.execute(CSVDownloadAction.java:61)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:99)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        (...)