860860 - don't fail when from attribute is missing
fixing
Traceback (most recent call last):
  File "/usr/bin/spacewalk-repo-sync", line 100, in <module>
    sys.exit(abs(main() or 0))
  File "/usr/bin/spacewalk-repo-sync", line 93, in main
    sync.sync()
  File
"/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/reposync.py", line
101, in sync
    self.import_updates(plugin, url)
  File
"/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/reposync.py", line
129, in import_updates
    self.upload_updates(notices)
  File
"/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/reposync.py", line
143, in upload_updates
    notice = self.fix_notice(notice)
  File
"/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/reposync.py", line
469, in fix_notice
    if "suse" in notice['from'].lower():
AttributeError: 'NoneType' object has no attribute 'lower'