The ip colum is numeric, do not cast parameter to string.
Addressing
2012-05-29 10:23:02,506 [TP-Processor3] ERROR com.redhat.rhn.common.db.datasource.CachedStatement - Error while processing cached statement sql: SELECT KSIPR.kickstart_id AS i
  FROM rhnKickstartIPRange KSIPR, rhnKSData KS
 WHERE KSIPR.org_id = ?
   AND KSIPR.min <= ?
   AND KSIPR.max >= ?
   AND KS.id = KSIPR.kickstart_id
ORDER BY KSIPR.min
com.redhat.rhn.common.db.WrappedSQLException: ERROR: operator does not exist: numeric <= character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.