create dir if it does not exist
Addresses
Traceback (most recent call last):
   File "./usr/lib64/python2.6/site-packages/spacewalk/server/apacheUploadServer.py", line 100, in _wrapper
     ret = function(req)
   File "./usr/share/rhn/upload_server/handlers/package_push/package_push.py", line 115, in handler
     self.packaging)
   File "./usr/lib64/python2.6/site-packages/spacewalk/server/rhnPackageUpload.py", line 45, in write_temp_file
     suffix=suffix)
   File "/usr/lib64/python2.6/tempfile.py", line 444, in NamedTemporaryFile
     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
   File "/usr/lib64/python2.6/tempfile.py", line 228, in _mkstemp_inner
     fd = _os.open(file, flags, 0600)
 OSError: [Errno 2] No such file or directory: '/var/spacewalk/packages/1/some-package.dpGPF'