1174627 - make sure columns are named according to the dto attributes
addressing:
com.redhat.rhn.common.util.MethodNotFoundException: Could not find method called: setFullListEvrRelease in class: com.redhat.rhn.frontend.dto.PackageListItem with params: [type: java.lang.String, value: 0.21.el7sat]
        at com.redhat.rhn.common.util.MethodUtil.callMethod(MethodUtil.java:200)
        at com.redhat.rhn.common.db.datasource.CachedStatement.addToObject(CachedStatement.java:776)
        at com.redhat.rhn.common.db.datasource.CachedStatement.processResultSet(CachedStatement.java:626)
        at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:474)
        at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:443)
        at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:345)
        at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:351)
        at com.redhat.rhn.common.db.datasource.CachedStatement.execute(CachedStatement.java:287)
        at com.redhat.rhn.common.db.datasource.SelectMode.execute(SelectMode.java:110)
        at com.redhat.rhn.manager.BaseManager.makeDataResult(BaseManager.java:57)
        at com.redhat.rhn.manager.rhnpackage.PackageManager.systemAvailablePackages(PackageManager.java:314)
        at com.redhat.rhn.frontend.action.rhnpackage.InstallPackageSetupAction.getDataResult(InstallPackageSetupAction.java:32)
        at com.redhat.rhn.frontend.action.rhnpackage.BaseSystemPackagesAction.execute(BaseSystemPackagesAction.java:83)

Conflicts:
	java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml