fix call of setCustomOptions()
setCustomOptions expects a String[] but ksdetails['custom_opts']
is a dict with keys "name" and "arguments". This results in a

ClassCastException: redstone.xmlrpc.XmlRpcStruct incompatible with java.lang.String