fixed errata export / import
fixing
Exception type <type 'exceptions.KeyError'>
...
  File "/usr/lib/python2.6/site-packages/spacewalk/satellite_tools/exporter/exportLib.py", line 1004, in set_iterator
    SimpleDumper(self._writer, 'rhn-erratum-bug-href', self._row['bug_href']),
KeyError: 'bug_href'

introduced in 307d2c5606ab10561acbfa3fda89b5c0a2671233