removed commented line which breaks build
fixing
error: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly
error: line 131: #%{__python} setup.py build