Exclude el-api.jar since it causes HTTP Status 500
There is an exception with this root cause:
java.lang.LinkageError: javax/servlet/jsp/JspApplicationContext.getExpressionFactory()Ljavax/el/ExpressionFactory;