Fix NoClassDefFoundError when opening notifications (#7556)
Fix NoClassDefFoundError when opening notifications

* Update Changelog
* Fix similar error that can be caused by an invalid custom mailer class
* Fix Sonarcloud issues