Add missing join in the count query for the packages list
This fixes the following error message when filtering all managed
packages (bsc#1233450):

    ERROR: missing FROM-clause entry for table "pn"