extend label in rhnContentSource table
addressing:
$ spacewalk-common-channels -v -u adminacct -a x86_64 'oraclelinux*'
Connecting to http://localhost/rpc/api
Password:
Base channel 'Oracle Linux 5 (x86_64)' - creating...
* Child channel 'Addons for Oracle Linux 5 (x86_64)' - creating...
* Child channel 'Oracle software addons for Oracle Linux 5 (x86_64)' - creating...
* Child channel 'Spacewalk 2.2 Client for Oracle Linux 5 (x86_64)' - creating...
* Child channel 'Latest Unbreakable Enterprise Kernel for Oracle Linux 5 (x86_64)' - creating...
Traceback (most recent call last):
  File "/usr/bin/spacewalk-common-channels", line 333, in <module>
    child_info['yumrepo_url'])
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1243, in request
    headers
xmlrpclib.ProtocolError: <ProtocolError for localhost/rpc/api: 500 Internal Server Error>

Conflicts:
	schema/spacewalk/common/tables/rhnContentSource.sql