don't convert ids to strings
fixing
ERROR:  operator does not exist: numeric = character varying at character 214
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  SELECT P.id AS ID,
               PN.name || '-' || evr_t_as_vre_simple(PE.evr) AS PACKAGE_NVRE,
               P.summary
...