No need to be autonomous when inserting to rhnArchType, only satellite-sync does it.
Addressing
  File "/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/sql_base.py", line 172, in executemany
    return apply(self._execute_wrapper, (self._executemany, ) + p, kw)
  File
"/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 282, in _execute_wrapper
    retval = apply(function, p, kw)
  File
"/usr/lib/python2.4/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 318, in _executemany
    self._real_cursor.executemany(self.sql, all_kwargs)
SQLStatementPrepareError: ('syntax error at or near "autonomous_transaction" at character 53\n', 0, '\n                declare\n                    pragma autonomous_transaction;\n                begin\n                    insert into rhnArchType (id, label, name)\n                    values (%(id)s, %(label)s, %(name)s);\n                    commit;\n                end;\n            ')