Use getActive() instead of isActive() for JavaBeans compliance (bsc#1043143) (#1213)
According to the Java Beans specification, the `is` prefix for methods
is only accepted for primitive type boolean, so Boolean must use the
general `get` prefix.

This is interpreted strictly in some JSP implementations, notably Tomcat
8.0.43, which produces the following error in
rhn/kickstart/KickstartDeleteAdvanced:

javax.servlet.ServletException: javax.servlet.jsp.JspException:
javax.el.PropertyNotFoundException: Property 'active' not readable on
type com.redhat.rhn.domain.kickstart.KickstartRawData

See
http://www.oracle.com/technetwork/java/javase/documentation/spec-136004.html
https://stackoverflow.com/a/13952656