948185 - fix system.listSystemEvents on PG
actions of configfiles.diff type caused:
java.lang.ClassCastException: [B cannot be cast to java.sql.Blob at
com.redhat.rhn.frontend.xmlrpc.system.SystemHandler.listSystemEvents(SystemHandler.java:2313)