obsolete only older (oracle) version of dobby
fixing yum upgrade failure
---> Package spacewalk-setup-postgresql.noarch 0:2.7.3-1.el7 will be an update
--> Processing Dependency: spacewalk-dobby for package: spacewalk-setup-postgresql-2.7.3-1.el7.noarch
Package spacewalk-dobby is obsoleted by spacewalk-oracle, but obsoleting package does not provide for requirements
--> Finished Dependency Resolution
Error: Package: spacewalk-setup-postgresql-2.7.3-1.el7.noarch (spacewalk-nightly)
           Requires: spacewalk-dobby
           Available: spacewalk-dobby-2.7.5-1.el7.noarch (spacewalk-nightly)
               spacewalk-dobby = 2.7.5-1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest