809936 - we need to insert NULLs to avoid vn_rhnserverhistory_details.
Addressing
IntegrityError: new row for relation "rhnserverhistory" violates check constraint "vn_rhnserverhistory_details"