Fix NoClassDefFoundError (bsc#988196)
This fixes the following error caused by IBM Java's ClassLoader:

java.lang.NoClassDefFoundError: com.suse.salt.netapi.datatypes.target.Target