tomcat in EPEL has been updated
fixing
...
Error: Package: tomcat-servlet-3.0-api-mvn-2.7.11-1.sw.noarch (group_spacewalkproject-epel6-addons)
           Requires: tomcat-servlet-3.0-api = 7.0.77
           Available: tomcat-servlet-3.0-api-7.0.78-1.el6.noarch (epel)
               tomcat-servlet-3.0-api = 7.0.78-1.el6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest